// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from "D:/code/@turbo/zhux-utils/node_modules/.pnpm/dumi@2.2.0_@babel+core@7.22.10_@types+node@14.18.28_@types+react@18.0.20_eslint@8.24.0_postcs_5sx7lkctg624cq6aha6t23msqy/node_modules/dumi/theme-default/slots/Logo/index.js"
