// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import {
  demos as dm0,
  frontmatter as fm0,
  toc as toc0,
  texts as txt0,
} from "D:/code/@turbo/zhux-utils/apps/zhux-site/docs/utils-doc/CreatePortalHelper.md?type=meta"
import {
  demos as dm1,
  frontmatter as fm1,
  toc as toc1,
  texts as txt1,
} from "D:/code/@turbo/zhux-utils/apps/zhux-site/docs/utils-doc/useWhyDidYouRender.md?type=meta"
import {
  demos as dm2,
  frontmatter as fm2,
  toc as toc2,
  texts as txt2,
} from "D:/code/@turbo/zhux-utils/apps/zhux-site/docs/utils-doc/ListenValueHelper.md?type=meta"
import {
  demos as dm3,
  frontmatter as fm3,
  toc as toc3,
  texts as txt3,
} from "D:/code/@turbo/zhux-utils/apps/zhux-site/docs/utils-doc/useCtrlComponent.md?type=meta"
import {
  demos as dm4,
  frontmatter as fm4,
  toc as toc4,
  texts as txt4,
} from "D:/code/@turbo/zhux-utils/apps/zhux-site/docs/utils-doc/useCustomFields.md?type=meta"
import {
  demos as dm5,
  frontmatter as fm5,
  toc as toc5,
  texts as txt5,
} from "D:/code/@turbo/zhux-utils/apps/zhux-site/docs/utils-doc/useStorageStore.md?type=meta"
import {
  demos as dm6,
  frontmatter as fm6,
  toc as toc6,
  texts as txt6,
} from "D:/code/@turbo/zhux-utils/apps/zhux-site/docs/utils-doc/useStorageValue.md?type=meta"
import {
  demos as dm7,
  frontmatter as fm7,
  toc as toc7,
  texts as txt7,
} from "D:/code/@turbo/zhux-utils/apps/zhux-site/docs/utils-doc/useWatchEffect.md?type=meta"
import {
  demos as dm8,
  frontmatter as fm8,
  toc as toc8,
  texts as txt8,
} from "D:/code/@turbo/zhux-utils/apps/zhux-site/docs/utils-doc/StorageHelper.md?type=meta"
import {
  demos as dm9,
  frontmatter as fm9,
  toc as toc9,
  texts as txt9,
} from "D:/code/@turbo/zhux-utils/apps/zhux-site/docs/utils-doc/useOnceEffect.md?type=meta"
import {
  demos as dm10,
  frontmatter as fm10,
  toc as toc10,
  texts as txt10,
} from "D:/code/@turbo/zhux-utils/apps/zhux-site/docs/utils-doc/usePagination.md?type=meta"
import {
  demos as dm11,
  frontmatter as fm11,
  toc as toc11,
  texts as txt11,
} from "D:/code/@turbo/zhux-utils/apps/zhux-site/docs/utils-doc/useScrollUtil.md?type=meta"
import {
  demos as dm12,
  frontmatter as fm12,
  toc as toc12,
  texts as txt12,
} from "D:/code/@turbo/zhux-utils/apps/zhux-site/docs/utils-doc/useStoreState.md?type=meta"
import {
  demos as dm13,
  frontmatter as fm13,
  toc as toc13,
  texts as txt13,
} from "D:/code/@turbo/zhux-utils/apps/zhux-site/docs/utils-doc/useAsyncMemo.md?type=meta"
import {
  demos as dm14,
  frontmatter as fm14,
  toc as toc14,
  texts as txt14,
} from "D:/code/@turbo/zhux-utils/apps/zhux-site/docs/utils-doc/CatchHelper.md?type=meta"
import {
  demos as dm15,
  frontmatter as fm15,
  toc as toc15,
  texts as txt15,
} from "D:/code/@turbo/zhux-utils/apps/zhux-site/docs/utils-doc/useDateTime.md?type=meta"
import {
  demos as dm16,
  frontmatter as fm16,
  toc as toc16,
  texts as txt16,
} from "D:/code/@turbo/zhux-utils/apps/zhux-site/docs/utils-doc/CommonUtil.md?type=meta"
import {
  demos as dm17,
  frontmatter as fm17,
  toc as toc17,
  texts as txt17,
} from "D:/code/@turbo/zhux-utils/apps/zhux-site/docs/utils-doc/useDialog.md?type=meta"
import {
  demos as dm18,
  frontmatter as fm18,
  toc as toc18,
  texts as txt18,
} from "D:/code/@turbo/zhux-utils/apps/zhux-site/docs/blog/align-justify.md?type=meta"
import {
  demos as dm19,
  frontmatter as fm19,
  toc as toc19,
  texts as txt19,
} from "D:/code/@turbo/zhux-utils/apps/zhux-site/docs/blog/githubActions.md?type=meta"
import {
  demos as dm20,
  frontmatter as fm20,
  toc as toc20,
  texts as txt20,
} from "D:/code/@turbo/zhux-utils/apps/zhux-site/docs/utils-doc/type.md?type=meta"
import {
  demos as dm21,
  frontmatter as fm21,
  toc as toc21,
  texts as txt21,
} from "D:/code/@turbo/zhux-utils/apps/zhux-site/docs/blog/hook-1.md?type=meta"
import {
  demos as dm22,
  frontmatter as fm22,
  toc as toc22,
  texts as txt22,
} from "D:/code/@turbo/zhux-utils/apps/zhux-site/docs/blog/hook-2.md?type=meta"
import {
  demos as dm23,
  frontmatter as fm23,
  toc as toc23,
  texts as txt23,
} from "D:/code/@turbo/zhux-utils/apps/zhux-site/docs/blog/resume.md?type=meta"
import {
  demos as dm24,
  frontmatter as fm24,
  toc as toc24,
  texts as txt24,
} from "D:/code/@turbo/zhux-utils/apps/zhux-site/docs/blog/rollup.md?type=meta"
import {
  demos as dm25,
  frontmatter as fm25,
  toc as toc25,
  texts as txt25,
} from "D:/code/@turbo/zhux-utils/apps/zhux-site/docs/blog/order.md?type=meta"
import {
  demos as dm26,
  frontmatter as fm26,
  toc as toc26,
  texts as txt26,
} from "D:/code/@turbo/zhux-utils/apps/zhux-site/docs/blog/blog.md?type=meta"
import {
  demos as dm27,
  frontmatter as fm27,
  toc as toc27,
  texts as txt27,
} from "D:/code/@turbo/zhux-utils/apps/zhux-site/docs/blog/lint.md?type=meta"
import {
  demos as dm28,
  frontmatter as fm28,
  toc as toc28,
  texts as txt28,
} from "D:/code/@turbo/zhux-utils/apps/zhux-site/docs/index.md?type=meta"

export { components } from "./atoms"
export { tabs } from "./tabs"

export const filesMeta = {
  "docs/utils-doc/CreatePortalHelper": {
    frontmatter: fm0,
    toc: toc0,
    texts: txt0,
    demos: dm0,
  },
  "docs/utils-doc/useWhyDidYouRender": {
    frontmatter: fm1,
    toc: toc1,
    texts: txt1,
    demos: dm1,
  },
  "docs/utils-doc/ListenValueHelper": {
    frontmatter: fm2,
    toc: toc2,
    texts: txt2,
    demos: dm2,
  },
  "docs/utils-doc/useCtrlComponent": {
    frontmatter: fm3,
    toc: toc3,
    texts: txt3,
    demos: dm3,
  },
  "docs/utils-doc/useCustomFields": {
    frontmatter: fm4,
    toc: toc4,
    texts: txt4,
    demos: dm4,
  },
  "docs/utils-doc/useStorageStore": {
    frontmatter: fm5,
    toc: toc5,
    texts: txt5,
    demos: dm5,
  },
  "docs/utils-doc/useStorageValue": {
    frontmatter: fm6,
    toc: toc6,
    texts: txt6,
    demos: dm6,
  },
  "docs/utils-doc/useWatchEffect": {
    frontmatter: fm7,
    toc: toc7,
    texts: txt7,
    demos: dm7,
  },
  "docs/utils-doc/StorageHelper": {
    frontmatter: fm8,
    toc: toc8,
    texts: txt8,
    demos: dm8,
  },
  "docs/utils-doc/useOnceEffect": {
    frontmatter: fm9,
    toc: toc9,
    texts: txt9,
    demos: dm9,
  },
  "docs/utils-doc/usePagination": {
    frontmatter: fm10,
    toc: toc10,
    texts: txt10,
    demos: dm10,
  },
  "docs/utils-doc/useScrollUtil": {
    frontmatter: fm11,
    toc: toc11,
    texts: txt11,
    demos: dm11,
  },
  "docs/utils-doc/useStoreState": {
    frontmatter: fm12,
    toc: toc12,
    texts: txt12,
    demos: dm12,
  },
  "docs/utils-doc/useAsyncMemo": {
    frontmatter: fm13,
    toc: toc13,
    texts: txt13,
    demos: dm13,
  },
  "docs/utils-doc/CatchHelper": {
    frontmatter: fm14,
    toc: toc14,
    texts: txt14,
    demos: dm14,
  },
  "docs/utils-doc/useDateTime": {
    frontmatter: fm15,
    toc: toc15,
    texts: txt15,
    demos: dm15,
  },
  "docs/utils-doc/CommonUtil": {
    frontmatter: fm16,
    toc: toc16,
    texts: txt16,
    demos: dm16,
  },
  "docs/utils-doc/useDialog": {
    frontmatter: fm17,
    toc: toc17,
    texts: txt17,
    demos: dm17,
  },
  "docs/blog/align-justify": {
    frontmatter: fm18,
    toc: toc18,
    texts: txt18,
    demos: dm18,
  },
  "docs/blog/githubActions": {
    frontmatter: fm19,
    toc: toc19,
    texts: txt19,
    demos: dm19,
  },
  "docs/utils-doc/type": {
    frontmatter: fm20,
    toc: toc20,
    texts: txt20,
    demos: dm20,
  },
  "docs/blog/hook-1": {
    frontmatter: fm21,
    toc: toc21,
    texts: txt21,
    demos: dm21,
  },
  "docs/blog/hook-2": {
    frontmatter: fm22,
    toc: toc22,
    texts: txt22,
    demos: dm22,
  },
  "docs/blog/resume": {
    frontmatter: fm23,
    toc: toc23,
    texts: txt23,
    demos: dm23,
  },
  "docs/blog/rollup": {
    frontmatter: fm24,
    toc: toc24,
    texts: txt24,
    demos: dm24,
  },
  "docs/blog/order": {
    frontmatter: fm25,
    toc: toc25,
    texts: txt25,
    demos: dm25,
  },
  "docs/blog/blog": {
    frontmatter: fm26,
    toc: toc26,
    texts: txt26,
    demos: dm26,
  },
  "docs/blog/lint": {
    frontmatter: fm27,
    toc: toc27,
    texts: txt27,
    demos: dm27,
  },
  "docs/index": {
    frontmatter: fm28,
    toc: toc28,
    texts: txt28,
    demos: dm28,
  },
}

// generate demos data in runtime, for reuse route.id to reduce bundle size
export const demos = Object.entries(filesMeta).reduce((acc, [id, meta]) => {
  // append route id to demo
  Object.values(meta.demos).forEach(demo => {
    demo.routeId = id
  })
  // merge demos
  Object.assign(acc, meta.demos)

  // remove demos from meta, to avoid deep clone demos in umi routes/children compatible logic
  delete meta.demos

  return acc
}, {})
