// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React, { useState, useEffect, useRef } from "react"
import { useOutlet, history } from "dumi"

import nprogress from "D:/code/@turbo/zhux-utils/node_modules/.pnpm/nprogress@0.2.0/node_modules/nprogress"
import "./nprogress.css"

import { SiteContext } from "D:/code/@turbo/zhux-utils/node_modules/.pnpm/dumi@2.2.0_@babel+core@7.22.10_@types+node@14.18.28_@types+react@18.0.20_eslint@8.24.0_postcs_5sx7lkctg624cq6aha6t23msqy/node_modules/dumi/dist/client/theme-api/context.js"
import { demos, components } from "../meta"
import { locales } from "../locales/config"

const entryExports = {}

export default function DumiContextWrapper() {
  const outlet = useOutlet()
  const [loading, setLoading] = useState(true)
  const prev = useRef(history.location.pathname)

  useEffect(() => {
    return history.listen(next => {
      if (next.location.pathname !== prev.current) {
        prev.current = next.location.pathname

        // mark loading when route change, page component will set false when loaded
        setLoading(true)

        // start nprogress
        nprogress.start()

        // scroll to top when route changed
        document.documentElement.scrollTo(0, 0)
      }
    })
  }, [])

  return (
    <SiteContext.Provider
      value={{
        pkg: {
          name: "zhux-site",
          description: "A static site based on dumi",
          version: "0.0.1",
          license: "MIT",
          authors: [],
        },
        historyType: "browser",
        entryExports,
        demos,
        components,
        locales,
        loading,
        setLoading,
        themeConfig: {
          footer: 'Copyright © 2023 | Powered by <a href="https://d.umijs.org" target="_blank" rel="noreferrer">dumi</a>',
          prefersColor: { default: "light", switch: true },
          nprogress: true,
          name: "ZHUX",
          logo: "https://s2.loli.net/2023/08/15/viFKg9krfsMJU2Y.png",
          socialLinks: { github: "https://github.com/stupidZhu/zhux-utils" },
        },
        _2_level_nav_available: true,
      }}
    >
      {outlet}
    </SiteContext.Provider>
  )
}
